### PR TITLE
Use my papers too!

### PR DESCRIPTION
**Pull request by jfbastien**
Because Tab said to:
https://twitter.com/tabatkins/status/983645231135494145

### CODE REVIEW

**Comment by jfbastien** [comment]
I'm guessing this is the right way to do it? Weird to be an org.

**Comment by foolip** [comment]
I think this will break when we attempt to call `get_organization('jfbastien')`. @tabatkins, seems like we need a user field? Or actually just the repo line? Yeah, I think that'll work :)

**Comment by tabatkins** [comment]
So I just implemented the code to support users, but I'm confused - @jfbastien, outside the "papers" repo that you're excluding, the only Bikeshed files in your repos are the tests in your Bikeshed fork, and then `jfbastien/wg21_p0333_improving_parallel_algorithms_exception_handling/proposals/D0000.bs`.

Did you perhaps actually mean to *only* include the "papers" repo?

**Comment by tabatkins** [comment]
Yes, `jfbastien/papers` contains a bunch of bs files, so I'm guessing that's what you meant.  Like I said in the earlier PR, the file format should be in our README. ^_^

**Comment by tabatkins** [comment]
Ok, so I submitted a PR with the correct line; when you accept it it'll autoclose this one.  As a bonus, this being the first "add repo" line, it'll make it clearer to future people how this works.

But also I'll add some guidance to the README and put a comment in this file pointing to it.

**Comment by jfbastien** [comment]
Oh derp yeah! I thought your syntax was a list of stuff, not excludes :)

**Pull request closed without merging**
